---
# Handlers pour le r√¥le Docker

- name: Restart docker
  systemd:
    name: docker
    state: restarted

- name: Reload docker
  systemd:
    name: docker
    daemon_reload: yes
    state: reloaded
